- name: "good first issue"
  color: "7057FF"
  description: "Good for newcomers"
- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "type: bug"
  color: "D73A4A"
  description: "Something isn't working"
- name: "type: discussion"
  color: "D4C5F9"
- name: "type: documention"
  color: "006B75"
  description: "Improvements or additions to documentation"
- name: "type: enhancement"
  color: "84B6EB"
  description: "New feature or request"
- name: "type: feature request"
  color: "FBCA04"
- name: "type: question"
  color: "D876E3"
  description: "Futher information is requested"

- name: "priority: critical"
  color: "B60205"
- name: "priority: high"
  color: "D93F0B"
- name: "priority: medium"
  color: "FBCA04"
- name: "priority: low"
  color: "0E8A16"

- name: "status: can't reproduce"
  color: "FEC1C1"
- name: "status: confirmed"
  color: "215CEA"
- name: "status: duplicate"
  color: "CFD3D7"
  description: "This issue or pull request already exists"
- name: "status: needs information"
  color: "FEF2C0"
  description: "Futher information is needed"
- name: "status: wont do/fix"
  color: "EEEEEE"
  description: "This will not be worked on"
