[workspace]
members = [
    "client",
    "server",
    "common",
    "bevy-test"
]
resolver = "2" # Important! wgpu/Bevy needs this!

[profile.release]
opt-level = 3
debug = false

[profile.dev]
opt-level = 3
debug = true

[profile.test]
opt-level = 3
